server:
  port: 3600
spring:
  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.PostgreSQL82Dialect
    defer-datasource-initialization: true
  datasource:
    url: ${RDS_EP}${RDS_DB}
    driver-class-name: org.postgresql.Driver
    username: ${RDS_USER}
    password: ${RDS_PASS}
  h2:
    console.enabled: false
