server:
  port: 8080
spring:
  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.PostgreSQL82Dialect
    defer-datasource-initialization: true
  datasource:
    url: jdbc:postgresql://aam-rds.c99du1nqfrmg.us-east-1.rds.amazonaws.com/AAM
    driver-class-name: org.postgresql.Driver
    username: postgres
    password: revature1
  h2:
    console.enabled: false
